version: "3"
services:
    node-container:
        build: ./
        ports:
            - "5000:3000"
        volumes:
            - ./:/server
            - /server/node_modules
        environment:
            - PORT=3000
        # env_file:
        # -./.env
