version: "3"
services:
    node-container:
        build: ./
        ports:
            - "3000:3000"
        environment:
            - PORT=3000
    mongoDB:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=myusername #<db_username>
            - MONGO_INITDB_ROOT_PASSWORD=mypassword #<db_password>
        volumes:
            - mongo-db:/data/db
volumes:
    mongo-db:
