version: "3"
services:
    node-container:
        build:
            context: ./
            args:
                NODE_ENV: production
        environment:
            - NODE_ENV=production
        command: node src/index.js
