version: "3"
services:
  api-server:
    build: ./
    image: nkvi/api-server
    ports:
      - "5000:4000"
    volumes:
      - ./:/server
      - /server/node_modules
    # environment:
    #   - PORT=3000
    env_file:
      - ./.env
  db-mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myusername #<db_username>
      - MONGO_INITDB_ROOT_PASSWORD=mypassword #<db_password>
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:


